lbs:
  source:
    download: 
      nsis-3.01-src.tar.bz2: "https://sourceforge.net/projects/nsis/files/NSIS%203/3.01/nsis-3.01-src.tar.bz2/download"
      nsis-3.01.zip: "https://sourceforge.net/projects/nsis/files/NSIS%203/3.01/nsis-3.01.zip/download"
